// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/9/2025, 6:48:57 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/sshar/Desktop/BLOG-APP/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/plugins/**/*.{js,ts,mjs}","C:/Users/sshar/Desktop/BLOG-APP/composables/**/*.{js,ts,mjs}","C:/Users/sshar/Desktop/BLOG-APP/utils/**/*.{js,ts,mjs}","C:/Users/sshar/Desktop/BLOG-APP/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/BLOG-APP/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;