// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/9/2025, 1:51:53 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/sshar/Desktop/blog-app-full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/plugins/**/*.{js,ts,mjs}","C:/Users/sshar/Desktop/blog-app-full/composables/**/*.{js,ts,mjs}","C:/Users/sshar/Desktop/blog-app-full/utils/**/*.{js,ts,mjs}","C:/Users/sshar/Desktop/blog-app-full/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sshar/Desktop/blog-app-full/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;